// Prepare the two photographs. Crops and scales them with ffmpeg, encodes them with
// our own JPEG encoder, and writes
//   src/media.js     the JPEG bytes (base64) and where things are in them
//   src/spectral.js  the Earth as a 171 × 171 grey image, which the synthesizer plays in generation 5
// usage: node tools/prep.mjs <as17-148-22727~orig.jpg> <Pale_Blue_Dot.png>
//   https://images-assets.nasa.gov/image/as17-148-22727/as17-148-22727~orig.jpg   (NASA, public domain)
//   https://upload.wikimedia.org/wikipedia/commons/7/73/Pale_Blue_Dot.png          (NASA/JPL, public domain)
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const JPEG = require(path.join(here, '../src/jpeg.js'));
const [earthSrc, dotSrc] = process.argv.slice(2);
if (!earthSrc || !dotSrc) { console.error('usage: node tools/prep.mjs <earth.jpg> <dot.png>'); process.exit(1); }

const raw = (src, filter, W, H) => execFileSync('ffmpeg', ['-v', 'error', '-i', src, '-vf', filter, '-pix_fmt', 'rgb24', '-f', 'rawvideo', '-'], { maxBuffer: 1 << 28 }).subarray(0, W * H * 3);

// The Blue Marble: the full frame is 4579 px square with the disk (≈3058 px across,
// centred near 2275, 2322). A 3600 px crop scaled to 720 gives a 612 px Earth.
const S = 720, CROP = 3600, CX = 500, CY = 530;
const earth = raw(earthSrc, `crop=${CROP}:${CROP}:${CX}:${CY},scale=${S}:${S}:flags=lanczos`, S, S);
const eJ = JPEG.encode(earth, S, S, { quality: 88, restart: S / 16, comment: 'AS17-148-22727' });
// disk geometry, measured on the 720 px image
let n = 0, sx = 0, sy = 0, x0 = S, x1 = 0;
for (let y = 0; y < S; y++) for (let x = 0; x < S; x++) {
  const i = (y * S + x) * 3, l = 0.299 * earth[i] + 0.587 * earth[i + 1] + 0.114 * earth[i + 2];
  if (l > 28) { n++; sx += x; sy += y; if (x < x0) x0 = x; if (x > x1) x1 = x; }
}
const disk = { cx: +(sx / n).toFixed(1), cy: +(sy / n).toFixed(1), r: +((x1 - x0 + 1) / 2).toFixed(1) };

// Pale Blue Dot: 453 × 614; the Earth is the pale speck at (343–344, 344)
const DW = 453, DH = 614;
const dot = raw(dotSrc, 'null', DW, DH);
const dJ = JPEG.encode(dot, DW, DH, { quality: 92, subsample: '444', comment: 'PIA00452' }); // 4:4:4, or the dot loses its blue to the sunbeam

// the Earth for the synthesizer: 171 columns (harmonics 10–180 of E♭1) × 171 rows (time)
const SP = 171;
const sp = new Uint8Array(SP * SP);
for (let r = 0; r < SP; r++) for (let c = 0; c < SP; c++) {
  let s = 0, k = 0;
  const ya = Math.floor(r * S / SP), yb = Math.floor((r + 1) * S / SP), xa = Math.floor(c * S / SP), xb = Math.floor((c + 1) * S / SP);
  for (let y = ya; y < yb; y++) for (let x = xa; x < xb; x++) { const i = (y * S + x) * 3; s += 0.299 * earth[i] + 0.587 * earth[i + 1] + 0.114 * earth[i + 2]; k++; }
  sp[r * SP + c] = Math.round(s / k);
}

const b64 = (b) => Buffer.from(b).toString('base64');
const media = `/* generated by tools/prep.mjs — do not edit */
var MEDIA = {
  earth: { jpeg: '${b64(eJ.bytes)}', W: ${S}, H: ${S}, disk: ${JSON.stringify(disk)}, file: 'as17-148-22727.jpg' },
  dot: { jpeg: '${b64(dJ.bytes)}', W: ${DW}, H: ${DH}, earth: [343.5, 344], file: 'PIA00452.jpg' },
};
`;
const spectral = `/* generated by tools/prep.mjs — do not edit */
var SPECTRAL = { w: ${SP}, h: ${SP}, grey: '${b64(sp)}' };
if (typeof module !== 'undefined' && module.exports) module.exports = SPECTRAL;
`;
fs.writeFileSync(path.join(here, '../src/media.js'), media);
fs.writeFileSync(path.join(here, '../src/spectral.js'), spectral);
console.log(`earth ${eJ.bytes.length} bytes (${eJ.restarts.length} restarts), disk ${JSON.stringify(disk)}`);
console.log(`dot   ${dJ.bytes.length} bytes`);
console.log(`media.js ${(media.length / 1024).toFixed(1)} KB, spectral.js ${(spectral.length / 1024).toFixed(1)} KB`);
